// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nkhqrqdiokaugyndimnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5raHFycWRpb2thdWd5bmRpbW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjQ1MTEsImV4cCI6MjA3NTUwMDUxMX0.k8_4A2GIeZ-L1fNjy6f-7t8S7LCnic-T2HktZFPG_RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);